# Generated by Django 5.2.15 on 2026-06-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_chapterfile_preview_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapter_type',
            field=models.CharField(choices=[('reading', 'Reading'), ('assignment', 'Assignment')], default='reading', max_length=20),
        ),
    ]
