# Generated by Django 5.2.15 on 2026-06-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_chapter_chapter_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail_mime_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
